name: Django CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Stack
      run: docker-compose -f docker/docker-compose-actions.yml up -d --build
    - name: Run tests
      run: docker-compose run --rm stoqs ./test.sh CHANGEME load noextraload
    - name: Tear down the Stack
      run: docker-compose -f docker/docker-compose-actions.yml down
